First implementation of the Sampler class
This is a copy/past of the notebook prototype into relevant files.
Currently not working
```
File ~/Documents/Work/Program/gammapy-dev/gammapy/modeling/sampler.py:44, in Sampler.run(self, datasets)
     43 def run(self, datasets):
---> 44     datasets, parameters = self._parse_datasets(datasets=datasets)
     45     parameters = parameters.free_parameters
     47     # create log likelihood function
     48     # need to remove prior penalty

File ~/Documents/Work/Program/gammapy-dev/gammapy/modeling/sampler.py:40, in Sampler._parse_datasets(datasets)
     37 from gammapy.datasets import Dataset, Datasets
     39 if isinstance(datasets, (list, Dataset)):
---> 40     datasets = Datasets(datasets)
     41 return datasets, datasets.parameters.free_parameters

TypeError: Can't instantiate abstract class Datasets with abstract methods __delitem__, __getitem__, __len__, __setitem__, insert
```

Signed-off-by: fabio acero <fabio.f.acero@gmail.com>